language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.2
  - 7.1
  - 7.0
  - hhvm

matrix:
    allow_failures:
        - php: hhvm
        - php: 5.2
        - php: 7.1
        - php: 7.0

script: phpunit tests/
